title: My Portfolio
author: "Stanford Kang'ethe"
email: stanfordkangethe@outlook.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Welcome I am Stanford Kangethe, A data Analyst.
  I am motivated to learn new things in tech and enthusiastic in life.   

# social links
twitter_username: kangethe_stan # DO NOT include the @ character, or else the build will fail!
github_username:  StanMungai # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
